name: build

on: 
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
      
    strategy:
      matrix:
        keyboard: [v1x, v1x_left]
        keymap: [default, via]

    steps:
      - name: Check out latest GMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          path: qmk_firmware
          submodules: true

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: recyclingPad

      - name: Copy config
        run: cp -r recyclingPad/qmk/recyclingpad qmk_firmware/keyboards

      - run: cd qmk_firmware && qmk compile --keyboard recyclingPad/${{matrix.keyboard}} --keymap ${{matrix.keymap}}
        
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.keyboard}}-${{matrix.keymap}}
          path: qmk_firmware/.build/${{matrix.keyboard}}-${{matrix.keymap}}.hex
          if-no-files-found: error
