name: build

on: 
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
      - name: Check out latest GMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          path: qmk_firmware
          submodules: true
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: recyclingPad
      - name: Copy config
        run: cp -r recyclingPad/qmk/recyclingpad qmk_firmware/keyboards
      - name: Build all recyclingPads
        shell: 'bash {0}'
        run: |
          cd qmk_firmware
          QMK_KEYBOARDS=$(qmk list-keyboards | grep recyclingpad)
          exit_code=0
          for KB in $QMK_KEYBOARDS; do
            qmk info -l --keyboard ${KB}
            QMK_KEYMAPS=$(qmk list-keymaps -kb ${KB})
            for KM in $QMK_KEYMAPS; do
              echo "building ${KB} - ${KM}"
              qmk compile --keyboard ${KB} --keymap ${KM}
              exit_code=$(($exit_code + $?))
            done
          done
          if [[ $exit_code -gt 255 ]]; then
              exit 255
          fi
          exit $exit_code
        
    - uses: actions/upload-artifact@v3
      with:
        name: latest-firmware
        path: qmk_firmware/.build/
        if-no-files-found: error
